language: php


matrix:
  fast_finish: true
    include:

      # Test the latest stable release
      - php: 7.1
      - php: 7.2
      - php: 7.3
      - php: 7.4

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml